version: "3.9"

services:
  nginx:
    build:
      context: .
    image: nginx:1.23.3
    environment:
      - "TIMEZONE=Asia/Shanghai"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.33.22.100
    ports:
      - "8100:80"
    #      - "8443:443"
    volumes:
      - ${WEB_ROOT}:/webroot/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  #    depends_on:
  #      - php

  #  php:
  #    image: php_fpm:8.1.17
  #    #        build:
  #    #            context: /Users/dannylee/Documents/works/railway-admin
  #    #            dockerfile: ./phpfpm/Dockerfile
  #    restart: always
  #    volumes:
  #      - ${WEB_ROOT}:/var/www/html/
  #      - ./phpfpm/php.ini:/usr/local/etc/php/php.ini
  #      - ./phpfpm/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  #      - ./phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
  #      - ./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
  #    networks:
  #      app_net:
  #        ipv4_address: 172.33.22.110

  chan-mgt-app:
    image: php_cli:8.2.4
    #    build:
    #      context: .
    #      dockerfile: ./images/hyperf/Dockerfile
    #    restart: no
    volumes:
      - ${SERV_ROOT}:/app/
      - ./phpcli/php.ini:/usr/local/etc/php/php.ini
      - ./phpcli/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./phpcli/conf.d/docker-php-ext-swoole.ini:/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
    ports:
      - "9501:9501"
      - "9502:9502"
    networks:
      app_net:
        ipv4_address: 172.33.22.120
    command: [ "php","/app/bin/run","start" ]
    depends_on:
      - redis
      - mysql

  redis:
    image: redis/redis-stack:6.2.6-v6
    restart: always
    ports:
      - "10043:6379"
      - "10042:8001"
    networks:
      app_net:
        ipv4_address: 172.33.22.130

  #  CREATE USER 'root'@'%' IDENTIFIED BY 'fuck123sql';
  #  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
  #  FLUSH PRIVILEGES;
  mysql:
    image: bitnami/mysql
    volumes:
      #      - ./mysql/my.cnf:/etc/my.cnf
      #      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/bitnami.my.cnf:/opt/bitnami/mysql/conf/my.cnf
      - ./data/mysql-data:/bitnami/mysql/data
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      explicit_defaults_for_timestamp: true
      lower_case_table_names: 1
      MYSQL_ROOT_PASSWORD: 'fuck123sql'
      MYSQL_ROOT_HOST: '%'
      MYSQL_MAX_CONNECTIONS: 200
    user: root
    ports:
      - "10031:3306"
    networks:
      app_net:
        ipv4_address: 172.33.22.170

  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=vcm_c
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      app_net:
        ipv4_address: 172.33.22.122

volumes:
  es_data:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.33.22.0/16
