version: "3.9"

services:
  nginx:
    build:
      context: .
    image: nginx:1.23.3
    environment:
      - "TIMEZONE=Asia/Shanghai"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.11.11.100
    ports:
      - "8100:80"
    volumes:
      - ${WEB_ROOT}:/webroot/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  #    depends_on:
  #      - php

  # docker化部署需要 否则不需要
  #  serv:
  #    image: php_cli:8.2.5
  #    #    build:
  #    #      context: .
  #    #      dockerfile: ./images/hyperf/Dockerfile
  #    #    restart: no
  #    volumes:
  #      - ${SERV_ROOT}:/app/
  #      - ./phpcli/php.ini:/usr/local/etc/php/php.ini
  #      - ./phpcli/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  #      - ./phpcli/conf.d/docker-php-ext-swoole.ini:/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
  #    ports:
  #      - "9501:9501"
  #      - "9502:9502"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.11.11.120
  #    command: [ "php","/app/bin/run","start" ]
  #    depends_on:
  #      - redis
  #      - mysql

  redis:
    image: redis/redis-stack:6.2.6-v6
    restart: always
    ports:
      - "16379:6379"
      - "18001:8001"
    networks:
      app_net:
        ipv4_address: 172.11.11.130
    environment:
      - TZ=Asia/Shanghai

  #  CREATE USER 'root'@'%' IDENTIFIED BY 'fuck123sql';
  #  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
  #  FLUSH PRIVILEGES;
  mysql:
    image: bitnami/mysql
    volumes:
      #      - ./mysql/my.cnf:/etc/my.cnf
      #      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/bitnami.my.cnf:/opt/bitnami/mysql/conf/my.cnf
      - ./data/mysql-data:/bitnami/mysql/data
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      explicit_defaults_for_timestamp: true
      lower_case_table_names: 1
      MYSQL_ROOT_PASSWORD: 'fuck123sql'
      MYSQL_ROOT_HOST: '%'
      MYSQL_MAX_CONNECTIONS: 200
    user: root
    ports:
      - "13306:3306"
    networks:
      app_net:
        ipv4_address: 172.11.11.170

  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=nav_rc
      - TZ=Asia/Shanghai
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "25672:5672"
      - "35672:15672"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 111111
        hard: 111111
    networks:
      app_net:
        ipv4_address: 172.11.11.122

volumes:
  es_data:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.11.11.0/16
